"""tao bang search

Revision ID: ce3cd5139bc8
Revises: 
Create Date: 2026-10-05 14:37:24.036031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce3cd5139bc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extension bỏ dấu tiếng Việt cho tìm kiếm toàn văn (BR-SE1-01); chủ database được phép tạo
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_refs',
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_table('hashtag_usages',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('hashtag', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('post_id', 'hashtag')
    )
    op.create_index('ix_hashtag_usages_tag_created', 'hashtag_usages', ['hashtag', 'created_at'], unique=False)
    op.create_table('post_index',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('popularity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_post_index_author_id'), 'post_index', ['author_id'], unique=False)
    op.create_index('ix_post_index_created', 'post_index', ['created_at'], unique=False)
    op.create_index('ix_post_index_search', 'post_index', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('trending_hashtags',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(length=50), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rank')
    )
    op.create_table('user_index',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('follower_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_index')
    op.drop_table('trending_hashtags')
    op.drop_index('ix_post_index_search', table_name='post_index', postgresql_using='gin')
    op.drop_index('ix_post_index_created', table_name='post_index')
    op.drop_index(op.f('ix_post_index_author_id'), table_name='post_index')
    op.drop_table('post_index')
    op.drop_index('ix_hashtag_usages_tag_created', table_name='hashtag_usages')
    op.drop_table('hashtag_usages')
    op.drop_table('block_refs')
    # ### end Alembic commands ###
