"""bo sung bang con lai theo erd

Revision ID: 5672c861de84
Revises: 7d58689a3811
Create Date: 2026-10-05 14:34:50.107246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5672c861de84'
down_revision: Union[str, Sequence[str], None] = '7d58689a3811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_index('ix_likes_post_created', 'likes', ['post_id', 'created_at'], unique=False)
    op.create_table('mentions',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('post_hashtags',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('hashtag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'hashtag_id')
    )
    op.create_index('ix_post_hashtags_hashtag', 'post_hashtags', ['hashtag_id'], unique=False)
    op.create_table('reposts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_index('ix_reposts_post', 'reposts', ['post_id'], unique=False)
    op.add_column('posts', sa.Column('root_id', sa.UUID(), nullable=True))
    # Kiểu enum mới của PostgreSQL phải tạo trước khi thêm cột (autogenerate không tự sinh)
    sa.Enum('EVERYONE', 'OFF', name='reply_permission').create(op.get_bind(), checkfirst=True)
    op.add_column('posts', sa.Column('reply_permission', sa.Enum('EVERYONE', 'OFF', name='reply_permission'), server_default='EVERYONE', nullable=False))
    op.add_column('posts', sa.Column('like_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('reply_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('repost_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_posts_root_id'), 'posts', ['root_id'], unique=False)
    op.create_foreign_key('fk_posts_root_id', 'posts', 'posts', ['root_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_posts_root_id', 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_root_id'), table_name='posts')
    op.drop_column('posts', 'edited_at')
    op.drop_column('posts', 'repost_count')
    op.drop_column('posts', 'reply_count')
    op.drop_column('posts', 'like_count')
    op.drop_column('posts', 'reply_permission')
    sa.Enum(name='reply_permission').drop(op.get_bind(), checkfirst=True)
    op.drop_column('posts', 'root_id')
    op.drop_index('ix_reposts_post', table_name='reposts')
    op.drop_table('reposts')
    op.drop_index('ix_post_hashtags_hashtag', table_name='post_hashtags')
    op.drop_table('post_hashtags')
    op.drop_table('mentions')
    op.drop_index('ix_likes_post_created', table_name='likes')
    op.drop_table('likes')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
