"""tao bang post

Revision ID: 7d58689a3811
Revises: 
Create Date: 2026-10-03 08:52:54.946533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d58689a3811'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='post_visibility'), nullable=False),
    sa.Column('removed_by', sa.UUID(), nullable=True),
    sa.Column('removal_reason', sa.Enum('SPAM', 'HARASSMENT', 'HATE', 'VIOLENCE', 'SENSITIVE', 'OTHER', name='report_reason'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_author_created', 'posts', ['author_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_parent_id'), 'posts', ['parent_id'], unique=False)
    op.create_table('post_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'VIDEO', name='media_type'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_media_post_id'), 'post_media', ['post_id'], unique=False)
    op.create_table('report_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DISMISSED', 'CLOSED', name='case_status'), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_cases_status'), 'report_cases', ['status'], unique=False)
    op.create_index('uq_report_cases_one_pending', 'report_cases', ['post_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('SPAM', 'HARASSMENT', 'HATE', 'VIOLENCE', 'SENSITIVE', 'OTHER', name='report_reason'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason <> 'OTHER' OR (description IS NOT NULL AND length(trim(description)) > 0)", name='ck_report_other_has_description'),
    sa.ForeignKeyConstraint(['case_id'], ['report_cases.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'post_id', name='uq_reports_reporter_post')
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('uq_report_cases_one_pending', table_name='report_cases', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_report_cases_status'), table_name='report_cases')
    op.drop_table('report_cases')
    op.drop_index(op.f('ix_post_media_post_id'), table_name='post_media')
    op.drop_table('post_media')
    op.drop_index(op.f('ix_posts_parent_id'), table_name='posts')
    op.drop_index('ix_posts_author_created', table_name='posts')
    op.drop_table('posts')
    # Xóa các kiểu enum của PostgreSQL (autogenerate không tự sinh)
    sa.Enum(name="case_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="media_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="report_reason").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="post_visibility").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
